name: rick_and_morty_app
description: A Very Good Project created by Very Good CLI.
version: 0.0.1+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  responsive_sizer: ^3.3.1
  flutter_animate: ^4.5.2
  go_router: ^14.8.1
  skeletonizer: ^1.4.3
  equatable: ^2.0.7
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.1
  flutter_svg: ^2.0.17
  dio: ^5.8.0+1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  auto_size_text: ^3.0.0

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/logos/
    - assets/icons/
    - assets/ilustrations/
